"""empty message

Revision ID: 01f6dbd98b8f
Revises: ee7b1c4bc291
Create Date: 2018-05-29 15:22:39.585335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f6dbd98b8f'
down_revision = 'ee7b1c4bc291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planing_period_templates')
    op.add_column('inventory_items', sa.Column('cp_plan_date_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventory_items', sa.Column('cp_plan_date_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('material_forecasts', sa.Column('diet_plan_item_id', sa.Integer(), nullable=True))
    op.add_column('material_forecasts', sa.Column('from_regular_consumption', sa.Boolean(), nullable=True))
    op.add_column('material_forecasts', sa.Column('plan_date_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('material_forecasts', sa.Column('plan_date_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('material_forecasts', sa.Column('quantity_per_day', sa.Float(), nullable=True))
    op.create_index(op.f('ix_material_forecasts_diet_plan_item_id'), 'material_forecasts', ['diet_plan_item_id'], unique=False)
    op.create_foreign_key(None, 'material_forecasts', 'diet_plan_items', ['diet_plan_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material_forecasts', type_='foreignkey')
    op.drop_index(op.f('ix_material_forecasts_diet_plan_item_id'), table_name='material_forecasts')
    op.drop_column('material_forecasts', 'quantity_per_day')
    op.drop_column('material_forecasts', 'plan_date_start')
    op.drop_column('material_forecasts', 'plan_date_end')
    op.drop_column('material_forecasts', 'from_regular_consumption')
    op.drop_column('material_forecasts', 'diet_plan_item_id')
    op.drop_column('inventory_items', 'cp_plan_date_start')
    op.drop_column('inventory_items', 'cp_plan_date_end')
    op.create_table('planing_period_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('week_no', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planing_period_templates_pkey')
    )
    # ### end Alembic commands ###
