"""empty message

Revision ID: 1e2e5fcf20a2
Revises: a3d1bcad9a5e
Create Date: 2018-05-26 17:28:57.208460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2e5fcf20a2'
down_revision = 'a3d1bcad9a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('diet_plan_items', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('diet_plans', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('food_composition', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('food_maingroup', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('food_processing_type', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('food_subgroup', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('food_weight_reference', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('inventories', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('inventory_items', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('material_forecasts', sa.Column('consumption_plan_item_id', sa.Integer(), nullable=True))
    op.add_column('material_forecasts', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_material_forecasts_consumption_plan_item_id'), 'material_forecasts', ['consumption_plan_item_id'], unique=False)
    op.create_foreign_key(None, 'material_forecasts', 'consumption_plan_items', ['consumption_plan_item_id'], ['id'])
    op.add_column('materials', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('nutrients', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('places', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('shopping_order_items', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('states', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('trade_items', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('units_of_measures', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user_group_association', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user_groups', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('default_consumption_plan_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['default_consumption_plan_id'])
    op.create_foreign_key(None, 'users', 'consumption_plans', ['default_consumption_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'default_consumption_plan_id')
    op.drop_column('users', 'created')
    op.drop_column('user_groups', 'created')
    op.drop_column('user_group_association', 'created')
    op.drop_column('units_of_measures', 'created')
    op.drop_column('trade_items', 'created')
    op.drop_column('states', 'created')
    op.drop_column('shopping_order_items', 'created')
    op.drop_column('places', 'created')
    op.drop_column('nutrients', 'created')
    op.drop_column('materials', 'created')
    op.drop_constraint(None, 'material_forecasts', type_='foreignkey')
    op.drop_index(op.f('ix_material_forecasts_consumption_plan_item_id'), table_name='material_forecasts')
    op.drop_column('material_forecasts', 'created')
    op.drop_column('material_forecasts', 'consumption_plan_item_id')
    op.drop_column('inventory_items', 'created')
    op.drop_column('inventories', 'created')
    op.drop_column('food_weight_reference', 'created')
    op.drop_column('food_subgroup', 'created')
    op.drop_column('food_processing_type', 'created')
    op.drop_column('food_maingroup', 'created')
    op.drop_column('food_composition', 'created')
    op.drop_column('diet_plans', 'created')
    op.drop_column('diet_plan_items', 'created')
    op.drop_column('countries', 'created')
    # ### end Alembic commands ###
