"""empty message

Revision ID: 23a4c374a568
Revises: 3693ea08402f
Create Date: 2018-06-01 11:21:17.527198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a4c374a568'
down_revision = '3693ea08402f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'consumption_plan_items', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'consumption_plans', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'diet_plan_items', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'diet_plans', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'food_composition', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'ingredients', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'inventories', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'inventory_items', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'material_forecasts', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'meals', 'users', ['owner_id'], ['id'])
    op.add_column('places', sa.Column('title', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'shopping_order_items', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'shopping_orders', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'user_group_association', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group_association', type_='foreignkey')
    op.drop_constraint(None, 'shopping_orders', type_='foreignkey')
    op.drop_constraint(None, 'shopping_order_items', type_='foreignkey')
    op.drop_column('places', 'title')
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.drop_constraint(None, 'material_forecasts', type_='foreignkey')
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_constraint(None, 'food_composition', type_='foreignkey')
    op.drop_constraint(None, 'diet_plans', type_='foreignkey')
    op.drop_constraint(None, 'diet_plan_items', type_='foreignkey')
    op.drop_constraint(None, 'consumption_plans', type_='foreignkey')
    op.drop_constraint(None, 'consumption_plan_items', type_='foreignkey')
    # ### end Alembic commands ###
