"""empty message

Revision ID: 3693ea08402f
Revises: 097c5812873f
Create Date: 2018-06-01 10:30:27.881364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3693ea08402f'
down_revision = '097c5812873f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('language_code', sa.String(length=8), nullable=False))
    op.add_column('materials', sa.Column('title', sa.String(length=160), nullable=True))
    op.add_column('nutrients', sa.Column('title', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrients', 'title')
    op.drop_column('materials', 'title')
    op.drop_column('materials', 'language_code')
    # ### end Alembic commands ###
