"""empty message

Revision ID: 3e02f72bec30
Revises: 904ccd6adbde
Create Date: 2018-05-27 21:35:17.748845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e02f72bec30'
down_revision = '904ccd6adbde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planing_period_templates')
    op.add_column('consumption_plan_items', sa.Column('inventory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'consumption_plan_items', 'inventories', ['inventory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consumption_plan_items', type_='foreignkey')
    op.drop_column('consumption_plan_items', 'inventory_id')
    op.create_table('planing_period_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('week_no', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planing_period_templates_pkey')
    )
    # ### end Alembic commands ###
