"""empty message

Revision ID: 40cf4fdb9b3d
Revises: 6230cb23b997
Create Date: 2018-08-13 21:09:08.610742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cf4fdb9b3d'
down_revision = '6230cb23b997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_material_forecasts_inventory_id'), 'material_forecasts', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_units_of_measures_uom'), 'units_of_measures', ['uom'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_of_measures_uom'), table_name='units_of_measures')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_index(op.f('ix_material_forecasts_inventory_id'), table_name='material_forecasts')
    # ### end Alembic commands ###
