"""empty message

Revision ID: 4136d500a5f3
Revises: 
Create Date: 2018-05-24 10:39:53.342434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4136d500a5f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('ignore_forecast', sa.Boolean(), nullable=True))
    op.drop_column('inventory_items', 'need_from_diet_plan')
    op.drop_column('inventory_items', 'need_additional')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('need_additional', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inventory_items', sa.Column('need_from_diet_plan', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('inventory_items', 'ignore_forecast')
    # ### end Alembic commands ###
