"""empty message

Revision ID: 41788bf9a785
Revises: 8c00cbd20973
Create Date: 2018-05-17 20:50:51.395637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41788bf9a785'
down_revision = '8c00cbd20973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    op.drop_table('foods')
    op.add_column('users', sa.Column('default_portions', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_portions')
    op.create_table('foods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titleEN', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('titleDE', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('bls_code', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('ndb_code', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('isBaseFood', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parentBaseFood', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uom_nutrient_value', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('food_maingroup_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('food_subgroup_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('food_processing_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('food_preparation_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('food_edible_weight_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['food_edible_weight_id'], ['food_weight_reference.id'], name='foods_food_edible_weight_id_fkey'),
    sa.ForeignKeyConstraint(['food_maingroup_id'], ['food_maingroup.id'], name='foods_food_maingroup_id_fkey'),
    sa.ForeignKeyConstraint(['food_preparation_type_id'], ['food_preparation_type.id'], name='foods_food_preparation_type_id_fkey'),
    sa.ForeignKeyConstraint(['food_processing_type_id'], ['food_processing_type.id'], name='foods_food_processing_type_id_fkey'),
    sa.ForeignKeyConstraint(['food_subgroup_id'], ['food_subgroup.id'], name='foods_food_subgroup_id_fkey'),
    sa.ForeignKeyConstraint(['parentBaseFood'], ['foods.id'], name='foods_parentBaseFood_fkey'),
    sa.ForeignKeyConstraint(['uom_nutrient_value'], ['units_of_measures.uom'], name='foods_uom_nutrient_value_fkey'),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_groups.id'], name='foods_user_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='foods_pkey')
    )
    op.create_table('goods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titleEN', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('titleDE', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_groups.id'], name='goods_user_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='goods_pkey')
    )
    # ### end Alembic commands ###
