"""empty message

Revision ID: 904ccd6adbde
Revises: 1e2e5fcf20a2
Create Date: 2018-05-26 23:39:42.085628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904ccd6adbde'
down_revision = '1e2e5fcf20a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumption_plan_items', sa.Column('day_in_month', sa.SmallInteger(), nullable=True))
    op.add_column('consumption_plan_items', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('consumption_plan_items', sa.Column('weekday', sa.SmallInteger(), nullable=True))
    op.create_foreign_key(None, 'consumption_plans', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'diet_plan_items', 'meals', ['meal_id'], ['id'])
    op.create_foreign_key(None, 'diet_plans', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'ingredients', 'meals', ['meal_id'], ['id'])
    op.create_foreign_key(None, 'inventories', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'shopping_orders', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'user_group_association', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group_association', type_='foreignkey')
    op.drop_constraint(None, 'shopping_orders', type_='foreignkey')
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_constraint(None, 'diet_plans', type_='foreignkey')
    op.drop_constraint(None, 'diet_plan_items', type_='foreignkey')
    op.drop_constraint(None, 'consumption_plans', type_='foreignkey')
    op.drop_column('consumption_plan_items', 'weekday')
    op.drop_column('consumption_plan_items', 'end_date')
    op.drop_column('consumption_plan_items', 'day_in_month')
    # ### end Alembic commands ###
