"""empty message

Revision ID: 90aabe787991
Revises: ed0f708512cd
Create Date: 2018-06-09 10:37:52.826188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90aabe787991'
down_revision = 'ed0f708512cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('op_plan_date_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventory_items', sa.Column('op_plan_date_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventory_items', sa.Column('op_quantity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'op_quantity')
    op.drop_column('inventory_items', 'op_plan_date_start')
    op.drop_column('inventory_items', 'op_plan_date_end')
    # ### end Alembic commands ###
