"""empty message

Revision ID: a3d1bcad9a5e
Revises: 4136d500a5f3
Create Date: 2018-05-26 14:48:36.887072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d1bcad9a5e'
down_revision = '4136d500a5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planing_period_templates')
    # ### end Alembic commands ###
    op.alter_column('diet_plan_items', 'plan_date', existing_type=sa.DATE(), type_=sa.TIMESTAMP(timezone=True))
    op.alter_column('material_forecasts', 'plan_date', existing_type=sa.TIMESTAMP(), type_=sa.TIMESTAMP(timezone=True))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planing_period_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('week_no', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planing_period_templates_pkey')
    )

    op.alter_column('diet_plan_items', 'plan_date', existing_type=sa.TIMESTAMP(timezone=True), type_=sa.DATE())
    op.alter_column('material_forecasts', 'plan_date', existing_type=sa.TIMESTAMP(timezone=True), type_=sa.TIMESTAMP())

    # ### end Alembic commands ###
