"""empty message

Revision ID: bd97958ce114
Revises: 01f6dbd98b8f
Create Date: 2018-05-30 17:57:00.339001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd97958ce114'
down_revision = '01f6dbd98b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planing_period_templates')
    op.add_column('material_forecasts', sa.Column('type', sa.SmallInteger(), nullable=False))
    op.drop_column('material_forecasts', 'from_regular_consumption')
    op.drop_column('material_forecasts', 'plan_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_forecasts', sa.Column('plan_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('material_forecasts', sa.Column('from_regular_consumption', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('material_forecasts', 'type')
    op.create_table('planing_period_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('week_no', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planing_period_templates_pkey')
    )
    # ### end Alembic commands ###
