"""empty message

Revision ID: cb89249aaf30
Revises: 40cf4fdb9b3d
Create Date: 2018-08-13 21:51:09.296539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb89249aaf30'
down_revision = '40cf4fdb9b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units_of_measures', sa.Column('is_base_uom', sa.Boolean(), nullable=True))
    op.add_column('units_of_measures', sa.Column('is_kitchen_uom', sa.Boolean(), nullable=True))
    op.add_column('units_of_measures', sa.Column('is_nutrient_uom', sa.Boolean(), nullable=True))
    op.add_column('units_of_measures', sa.Column('is_stock_uom', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units_of_measures', 'is_stock_uom')
    op.drop_column('units_of_measures', 'is_nutrient_uom')
    op.drop_column('units_of_measures', 'is_kitchen_uom')
    op.drop_column('units_of_measures', 'is_base_uom')
    # ### end Alembic commands ###
