"""empty message

Revision ID: cbc7ddbf5d85
Revises: 93cd4fb6780a
Create Date: 2018-06-18 17:16:26.201599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbc7ddbf5d85'
down_revision = '93cd4fb6780a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumption_plan_items')
    op.drop_table('consumption_plans')
    op.add_column('shopping_orders', sa.Column('type', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_orders', 'type')
    op.create_table('consumption_plans',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('consumption_plans_id_seq'::regclass)"), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='consumption_plans_creator_id_fkey'),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_groups.id'], name='consumption_plans_user_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='consumption_plans_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('consumption_plan_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('consumption_plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('quantity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('plan_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('period', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('weekday', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('day_in_month', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['consumption_plan_id'], ['consumption_plans.id'], name='consumption_plan_items_consumption_plan_id_fkey'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], name='consumption_plan_items_inventory_id_fkey'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='consumption_plan_items_material_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='consumption_plan_items_pkey')
    )
    # ### end Alembic commands ###
