"""empty message

Revision ID: e2047def1a8a
Revises: aedb720adcd9
Create Date: 2018-06-05 23:34:18.130972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2047def1a8a'
down_revision = 'aedb720adcd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'status')
    op.drop_column('inventory_items', 'titleDE')
    op.drop_column('materials', 'titleDE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('titleDE', sa.VARCHAR(length=160), autoincrement=False, nullable=True))
    op.add_column('inventory_items', sa.Column('titleDE', sa.VARCHAR(length=160), autoincrement=False, nullable=True))
    op.add_column('inventory_items', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
