"""empty message

Revision ID: e9cf17ba2270
Revises: 23a4c374a568
Create Date: 2018-06-01 16:31:42.214313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cf17ba2270'
down_revision = '23a4c374a568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('quantity_conversion_factor', sa.Float(), nullable=True))
    op.add_column('inventory_items', sa.Column('quantity_issue', sa.Float(), nullable=True))
    op.add_column('inventory_items', sa.Column('quantity_stock', sa.Float(), nullable=True))
    op.add_column('inventory_items', sa.Column('uom_base_id', sa.String(length=5), nullable=False))
    op.add_column('inventory_items', sa.Column('uom_stock_id', sa.String(length=5), nullable=False))
    op.create_foreign_key(None, 'inventory_items', 'units_of_measures', ['uom_base_id'], ['uom'])
    op.create_foreign_key(None, 'inventory_items', 'units_of_measures', ['uom_stock_id'], ['uom'])
    op.add_column('materials', sa.Column('uom_base_id', sa.String(length=5), nullable=True))
    op.add_column('materials', sa.Column('uom_issue_id', sa.String(length=5), nullable=True))
    op.create_foreign_key(None, 'materials', 'units_of_measures', ['uom_issue_id'], ['uom'])
    op.create_foreign_key(None, 'materials', 'units_of_measures', ['uom_base_id'], ['uom'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_column('materials', 'uom_issue_id')
    op.drop_column('materials', 'uom_base_id')
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'uom_stock_id')
    op.drop_column('inventory_items', 'uom_base_id')
    op.drop_column('inventory_items', 'quantity_stock')
    op.drop_column('inventory_items', 'quantity_issue')
    op.drop_column('inventory_items', 'quantity_conversion_factor')
    # ### end Alembic commands ###
