"""empty message

Revision ID: ed0f708512cd
Revises: e2047def1a8a
Create Date: 2018-06-06 14:03:53.832891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0f708512cd'
down_revision = 'e2047def1a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'consumption_plan_items', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'diet_plan_items', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'food_composition', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'ingredients', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'material_forecasts', 'materials', ['material_id'], ['id'])
    op.add_column('materials', sa.Column('ndb_title', sa.String(length=160), nullable=True))
    op.create_foreign_key(None, 'shopping_order_items', 'materials', ['material_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_order_items', type_='foreignkey')
    op.drop_column('materials', 'ndb_title')
    op.drop_constraint(None, 'material_forecasts', type_='foreignkey')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_constraint(None, 'food_composition', type_='foreignkey')
    op.drop_constraint(None, 'diet_plan_items', type_='foreignkey')
    op.drop_constraint(None, 'consumption_plan_items', type_='foreignkey')
    # ### end Alembic commands ###
