"""empty message

Revision ID: f7664d991f83
Revises: 90aabe787991
Create Date: 2018-06-09 11:12:52.475109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7664d991f83'
down_revision = '90aabe787991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('quantity_base_user', sa.Float(), nullable=True))
    op.add_column('inventory_items', sa.Column('quantity_stock_user', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'quantity_stock_user')
    op.drop_column('inventory_items', 'quantity_base_user')
    # ### end Alembic commands ###
